// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Employee.proto

package com.example.httpserver.protobuf;

public final class EmployeeProto {
  private EmployeeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EmployeeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string firstname = 1;
    /**
     * <code>required string firstname = 1;</code>
     */
    boolean hasFirstname();
    /**
     * <code>required string firstname = 1;</code>
     */
    java.lang.String getFirstname();
    /**
     * <code>required string firstname = 1;</code>
     */
    com.google.protobuf.ByteString
        getFirstnameBytes();

    // optional string lastname = 2;
    /**
     * <code>optional string lastname = 2;</code>
     */
    boolean hasLastname();
    /**
     * <code>optional string lastname = 2;</code>
     */
    java.lang.String getLastname();
    /**
     * <code>optional string lastname = 2;</code>
     */
    com.google.protobuf.ByteString
        getLastnameBytes();

    // required int32 id = 3;
    /**
     * <code>required int32 id = 3;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 3;</code>
     */
    int getId();

    // optional double salary = 4 [default = 100000];
    /**
     * <code>optional double salary = 4 [default = 100000];</code>
     */
    boolean hasSalary();
    /**
     * <code>optional double salary = 4 [default = 100000];</code>
     */
    double getSalary();

    // repeated .Department dept = 5;
    /**
     * <code>repeated .Department dept = 5;</code>
     */
    java.util.List<com.example.httpserver.protobuf.EmployeeProto.Department> 
        getDeptList();
    /**
     * <code>repeated .Department dept = 5;</code>
     */
    com.example.httpserver.protobuf.EmployeeProto.Department getDept(int index);
    /**
     * <code>repeated .Department dept = 5;</code>
     */
    int getDeptCount();
    /**
     * <code>repeated .Department dept = 5;</code>
     */
    java.util.List<? extends com.example.httpserver.protobuf.EmployeeProto.DepartmentOrBuilder> 
        getDeptOrBuilderList();
    /**
     * <code>repeated .Department dept = 5;</code>
     */
    com.example.httpserver.protobuf.EmployeeProto.DepartmentOrBuilder getDeptOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Employee}
   */
  public static final class Employee extends
      com.google.protobuf.GeneratedMessage
      implements EmployeeOrBuilder {
    // Use Employee.newBuilder() to construct.
    private Employee(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Employee(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Employee defaultInstance;
    public static Employee getDefaultInstance() {
      return defaultInstance;
    }

    public Employee getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Employee(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              firstname_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              lastname_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              id_ = input.readInt32();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              salary_ = input.readDouble();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                dept_ = new java.util.ArrayList<com.example.httpserver.protobuf.EmployeeProto.Department>();
                mutable_bitField0_ |= 0x00000010;
              }
              dept_.add(input.readMessage(com.example.httpserver.protobuf.EmployeeProto.Department.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          dept_ = java.util.Collections.unmodifiableList(dept_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.httpserver.protobuf.EmployeeProto.internal_static_Employee_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.httpserver.protobuf.EmployeeProto.internal_static_Employee_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.httpserver.protobuf.EmployeeProto.Employee.class, com.example.httpserver.protobuf.EmployeeProto.Employee.Builder.class);
    }

    public static com.google.protobuf.Parser<Employee> PARSER =
        new com.google.protobuf.AbstractParser<Employee>() {
      public Employee parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Employee(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Employee> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string firstname = 1;
    public static final int FIRSTNAME_FIELD_NUMBER = 1;
    private java.lang.Object firstname_;
    /**
     * <code>required string firstname = 1;</code>
     */
    public boolean hasFirstname() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string firstname = 1;</code>
     */
    public java.lang.String getFirstname() {
      java.lang.Object ref = firstname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          firstname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string firstname = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFirstnameBytes() {
      java.lang.Object ref = firstname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string lastname = 2;
    public static final int LASTNAME_FIELD_NUMBER = 2;
    private java.lang.Object lastname_;
    /**
     * <code>optional string lastname = 2;</code>
     */
    public boolean hasLastname() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string lastname = 2;</code>
     */
    public java.lang.String getLastname() {
      java.lang.Object ref = lastname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          lastname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string lastname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLastnameBytes() {
      java.lang.Object ref = lastname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 id = 3;
    public static final int ID_FIELD_NUMBER = 3;
    private int id_;
    /**
     * <code>required int32 id = 3;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 id = 3;</code>
     */
    public int getId() {
      return id_;
    }

    // optional double salary = 4 [default = 100000];
    public static final int SALARY_FIELD_NUMBER = 4;
    private double salary_;
    /**
     * <code>optional double salary = 4 [default = 100000];</code>
     */
    public boolean hasSalary() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional double salary = 4 [default = 100000];</code>
     */
    public double getSalary() {
      return salary_;
    }

    // repeated .Department dept = 5;
    public static final int DEPT_FIELD_NUMBER = 5;
    private java.util.List<com.example.httpserver.protobuf.EmployeeProto.Department> dept_;
    /**
     * <code>repeated .Department dept = 5;</code>
     */
    public java.util.List<com.example.httpserver.protobuf.EmployeeProto.Department> getDeptList() {
      return dept_;
    }
    /**
     * <code>repeated .Department dept = 5;</code>
     */
    public java.util.List<? extends com.example.httpserver.protobuf.EmployeeProto.DepartmentOrBuilder> 
        getDeptOrBuilderList() {
      return dept_;
    }
    /**
     * <code>repeated .Department dept = 5;</code>
     */
    public int getDeptCount() {
      return dept_.size();
    }
    /**
     * <code>repeated .Department dept = 5;</code>
     */
    public com.example.httpserver.protobuf.EmployeeProto.Department getDept(int index) {
      return dept_.get(index);
    }
    /**
     * <code>repeated .Department dept = 5;</code>
     */
    public com.example.httpserver.protobuf.EmployeeProto.DepartmentOrBuilder getDeptOrBuilder(
        int index) {
      return dept_.get(index);
    }

    private void initFields() {
      firstname_ = "";
      lastname_ = "";
      id_ = 0;
      salary_ = 100000D;
      dept_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasFirstname()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getDeptCount(); i++) {
        if (!getDept(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFirstnameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getLastnameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, id_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, salary_);
      }
      for (int i = 0; i < dept_.size(); i++) {
        output.writeMessage(5, dept_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFirstnameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getLastnameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, id_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, salary_);
      }
      for (int i = 0; i < dept_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, dept_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.example.httpserver.protobuf.EmployeeProto.Employee parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.httpserver.protobuf.EmployeeProto.Employee parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.httpserver.protobuf.EmployeeProto.Employee parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.httpserver.protobuf.EmployeeProto.Employee parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.httpserver.protobuf.EmployeeProto.Employee parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.httpserver.protobuf.EmployeeProto.Employee parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.example.httpserver.protobuf.EmployeeProto.Employee parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.example.httpserver.protobuf.EmployeeProto.Employee parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.example.httpserver.protobuf.EmployeeProto.Employee parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.httpserver.protobuf.EmployeeProto.Employee parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.example.httpserver.protobuf.EmployeeProto.Employee prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Employee}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.example.httpserver.protobuf.EmployeeProto.EmployeeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.httpserver.protobuf.EmployeeProto.internal_static_Employee_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.httpserver.protobuf.EmployeeProto.internal_static_Employee_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.httpserver.protobuf.EmployeeProto.Employee.class, com.example.httpserver.protobuf.EmployeeProto.Employee.Builder.class);
      }

      // Construct using com.example.httpserver.protobuf.EmployeeProto.Employee.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDeptFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        firstname_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        lastname_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        salary_ = 100000D;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (deptBuilder_ == null) {
          dept_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          deptBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.httpserver.protobuf.EmployeeProto.internal_static_Employee_descriptor;
      }

      public com.example.httpserver.protobuf.EmployeeProto.Employee getDefaultInstanceForType() {
        return com.example.httpserver.protobuf.EmployeeProto.Employee.getDefaultInstance();
      }

      public com.example.httpserver.protobuf.EmployeeProto.Employee build() {
        com.example.httpserver.protobuf.EmployeeProto.Employee result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.httpserver.protobuf.EmployeeProto.Employee buildPartial() {
        com.example.httpserver.protobuf.EmployeeProto.Employee result = new com.example.httpserver.protobuf.EmployeeProto.Employee(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.firstname_ = firstname_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.lastname_ = lastname_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.salary_ = salary_;
        if (deptBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            dept_ = java.util.Collections.unmodifiableList(dept_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.dept_ = dept_;
        } else {
          result.dept_ = deptBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.httpserver.protobuf.EmployeeProto.Employee) {
          return mergeFrom((com.example.httpserver.protobuf.EmployeeProto.Employee)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.httpserver.protobuf.EmployeeProto.Employee other) {
        if (other == com.example.httpserver.protobuf.EmployeeProto.Employee.getDefaultInstance()) return this;
        if (other.hasFirstname()) {
          bitField0_ |= 0x00000001;
          firstname_ = other.firstname_;
          onChanged();
        }
        if (other.hasLastname()) {
          bitField0_ |= 0x00000002;
          lastname_ = other.lastname_;
          onChanged();
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasSalary()) {
          setSalary(other.getSalary());
        }
        if (deptBuilder_ == null) {
          if (!other.dept_.isEmpty()) {
            if (dept_.isEmpty()) {
              dept_ = other.dept_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureDeptIsMutable();
              dept_.addAll(other.dept_);
            }
            onChanged();
          }
        } else {
          if (!other.dept_.isEmpty()) {
            if (deptBuilder_.isEmpty()) {
              deptBuilder_.dispose();
              deptBuilder_ = null;
              dept_ = other.dept_;
              bitField0_ = (bitField0_ & ~0x00000010);
              deptBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDeptFieldBuilder() : null;
            } else {
              deptBuilder_.addAllMessages(other.dept_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFirstname()) {
          
          return false;
        }
        if (!hasId()) {
          
          return false;
        }
        for (int i = 0; i < getDeptCount(); i++) {
          if (!getDept(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.httpserver.protobuf.EmployeeProto.Employee parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.httpserver.protobuf.EmployeeProto.Employee) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string firstname = 1;
      private java.lang.Object firstname_ = "";
      /**
       * <code>required string firstname = 1;</code>
       */
      public boolean hasFirstname() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string firstname = 1;</code>
       */
      public java.lang.String getFirstname() {
        java.lang.Object ref = firstname_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          firstname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string firstname = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFirstnameBytes() {
        java.lang.Object ref = firstname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string firstname = 1;</code>
       */
      public Builder setFirstname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        firstname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string firstname = 1;</code>
       */
      public Builder clearFirstname() {
        bitField0_ = (bitField0_ & ~0x00000001);
        firstname_ = getDefaultInstance().getFirstname();
        onChanged();
        return this;
      }
      /**
       * <code>required string firstname = 1;</code>
       */
      public Builder setFirstnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        firstname_ = value;
        onChanged();
        return this;
      }

      // optional string lastname = 2;
      private java.lang.Object lastname_ = "";
      /**
       * <code>optional string lastname = 2;</code>
       */
      public boolean hasLastname() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string lastname = 2;</code>
       */
      public java.lang.String getLastname() {
        java.lang.Object ref = lastname_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          lastname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string lastname = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLastnameBytes() {
        java.lang.Object ref = lastname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string lastname = 2;</code>
       */
      public Builder setLastname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        lastname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string lastname = 2;</code>
       */
      public Builder clearLastname() {
        bitField0_ = (bitField0_ & ~0x00000002);
        lastname_ = getDefaultInstance().getLastname();
        onChanged();
        return this;
      }
      /**
       * <code>optional string lastname = 2;</code>
       */
      public Builder setLastnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        lastname_ = value;
        onChanged();
        return this;
      }

      // required int32 id = 3;
      private int id_ ;
      /**
       * <code>required int32 id = 3;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 id = 3;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 3;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000004;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 3;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        id_ = 0;
        onChanged();
        return this;
      }

      // optional double salary = 4 [default = 100000];
      private double salary_ = 100000D;
      /**
       * <code>optional double salary = 4 [default = 100000];</code>
       */
      public boolean hasSalary() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional double salary = 4 [default = 100000];</code>
       */
      public double getSalary() {
        return salary_;
      }
      /**
       * <code>optional double salary = 4 [default = 100000];</code>
       */
      public Builder setSalary(double value) {
        bitField0_ |= 0x00000008;
        salary_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double salary = 4 [default = 100000];</code>
       */
      public Builder clearSalary() {
        bitField0_ = (bitField0_ & ~0x00000008);
        salary_ = 100000D;
        onChanged();
        return this;
      }

      // repeated .Department dept = 5;
      private java.util.List<com.example.httpserver.protobuf.EmployeeProto.Department> dept_ =
        java.util.Collections.emptyList();
      private void ensureDeptIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          dept_ = new java.util.ArrayList<com.example.httpserver.protobuf.EmployeeProto.Department>(dept_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.example.httpserver.protobuf.EmployeeProto.Department, com.example.httpserver.protobuf.EmployeeProto.Department.Builder, com.example.httpserver.protobuf.EmployeeProto.DepartmentOrBuilder> deptBuilder_;

      /**
       * <code>repeated .Department dept = 5;</code>
       */
      public java.util.List<com.example.httpserver.protobuf.EmployeeProto.Department> getDeptList() {
        if (deptBuilder_ == null) {
          return java.util.Collections.unmodifiableList(dept_);
        } else {
          return deptBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Department dept = 5;</code>
       */
      public int getDeptCount() {
        if (deptBuilder_ == null) {
          return dept_.size();
        } else {
          return deptBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Department dept = 5;</code>
       */
      public com.example.httpserver.protobuf.EmployeeProto.Department getDept(int index) {
        if (deptBuilder_ == null) {
          return dept_.get(index);
        } else {
          return deptBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Department dept = 5;</code>
       */
      public Builder setDept(
          int index, com.example.httpserver.protobuf.EmployeeProto.Department value) {
        if (deptBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDeptIsMutable();
          dept_.set(index, value);
          onChanged();
        } else {
          deptBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Department dept = 5;</code>
       */
      public Builder setDept(
          int index, com.example.httpserver.protobuf.EmployeeProto.Department.Builder builderForValue) {
        if (deptBuilder_ == null) {
          ensureDeptIsMutable();
          dept_.set(index, builderForValue.build());
          onChanged();
        } else {
          deptBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Department dept = 5;</code>
       */
      public Builder addDept(com.example.httpserver.protobuf.EmployeeProto.Department value) {
        if (deptBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDeptIsMutable();
          dept_.add(value);
          onChanged();
        } else {
          deptBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Department dept = 5;</code>
       */
      public Builder addDept(
          int index, com.example.httpserver.protobuf.EmployeeProto.Department value) {
        if (deptBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDeptIsMutable();
          dept_.add(index, value);
          onChanged();
        } else {
          deptBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Department dept = 5;</code>
       */
      public Builder addDept(
          com.example.httpserver.protobuf.EmployeeProto.Department.Builder builderForValue) {
        if (deptBuilder_ == null) {
          ensureDeptIsMutable();
          dept_.add(builderForValue.build());
          onChanged();
        } else {
          deptBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Department dept = 5;</code>
       */
      public Builder addDept(
          int index, com.example.httpserver.protobuf.EmployeeProto.Department.Builder builderForValue) {
        if (deptBuilder_ == null) {
          ensureDeptIsMutable();
          dept_.add(index, builderForValue.build());
          onChanged();
        } else {
          deptBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Department dept = 5;</code>
       */
      public Builder addAllDept(
          java.lang.Iterable<? extends com.example.httpserver.protobuf.EmployeeProto.Department> values) {
        if (deptBuilder_ == null) {
          ensureDeptIsMutable();
          super.addAll(values, dept_);
          onChanged();
        } else {
          deptBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Department dept = 5;</code>
       */
      public Builder clearDept() {
        if (deptBuilder_ == null) {
          dept_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          deptBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Department dept = 5;</code>
       */
      public Builder removeDept(int index) {
        if (deptBuilder_ == null) {
          ensureDeptIsMutable();
          dept_.remove(index);
          onChanged();
        } else {
          deptBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Department dept = 5;</code>
       */
      public com.example.httpserver.protobuf.EmployeeProto.Department.Builder getDeptBuilder(
          int index) {
        return getDeptFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Department dept = 5;</code>
       */
      public com.example.httpserver.protobuf.EmployeeProto.DepartmentOrBuilder getDeptOrBuilder(
          int index) {
        if (deptBuilder_ == null) {
          return dept_.get(index);  } else {
          return deptBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Department dept = 5;</code>
       */
      public java.util.List<? extends com.example.httpserver.protobuf.EmployeeProto.DepartmentOrBuilder> 
           getDeptOrBuilderList() {
        if (deptBuilder_ != null) {
          return deptBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(dept_);
        }
      }
      /**
       * <code>repeated .Department dept = 5;</code>
       */
      public com.example.httpserver.protobuf.EmployeeProto.Department.Builder addDeptBuilder() {
        return getDeptFieldBuilder().addBuilder(
            com.example.httpserver.protobuf.EmployeeProto.Department.getDefaultInstance());
      }
      /**
       * <code>repeated .Department dept = 5;</code>
       */
      public com.example.httpserver.protobuf.EmployeeProto.Department.Builder addDeptBuilder(
          int index) {
        return getDeptFieldBuilder().addBuilder(
            index, com.example.httpserver.protobuf.EmployeeProto.Department.getDefaultInstance());
      }
      /**
       * <code>repeated .Department dept = 5;</code>
       */
      public java.util.List<com.example.httpserver.protobuf.EmployeeProto.Department.Builder> 
           getDeptBuilderList() {
        return getDeptFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.example.httpserver.protobuf.EmployeeProto.Department, com.example.httpserver.protobuf.EmployeeProto.Department.Builder, com.example.httpserver.protobuf.EmployeeProto.DepartmentOrBuilder> 
          getDeptFieldBuilder() {
        if (deptBuilder_ == null) {
          deptBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.example.httpserver.protobuf.EmployeeProto.Department, com.example.httpserver.protobuf.EmployeeProto.Department.Builder, com.example.httpserver.protobuf.EmployeeProto.DepartmentOrBuilder>(
                  dept_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          dept_ = null;
        }
        return deptBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Employee)
    }

    static {
      defaultInstance = new Employee(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Employee)
  }

  public interface DepartmentOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 deptid = 1;
    /**
     * <code>required int32 deptid = 1;</code>
     */
    boolean hasDeptid();
    /**
     * <code>required int32 deptid = 1;</code>
     */
    int getDeptid();

    // required string deptname = 2;
    /**
     * <code>required string deptname = 2;</code>
     */
    boolean hasDeptname();
    /**
     * <code>required string deptname = 2;</code>
     */
    java.lang.String getDeptname();
    /**
     * <code>required string deptname = 2;</code>
     */
    com.google.protobuf.ByteString
        getDeptnameBytes();
  }
  /**
   * Protobuf type {@code Department}
   */
  public static final class Department extends
      com.google.protobuf.GeneratedMessage
      implements DepartmentOrBuilder {
    // Use Department.newBuilder() to construct.
    private Department(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Department(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Department defaultInstance;
    public static Department getDefaultInstance() {
      return defaultInstance;
    }

    public Department getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Department(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              deptid_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              deptname_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.httpserver.protobuf.EmployeeProto.internal_static_Department_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.httpserver.protobuf.EmployeeProto.internal_static_Department_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.httpserver.protobuf.EmployeeProto.Department.class, com.example.httpserver.protobuf.EmployeeProto.Department.Builder.class);
    }

    public static com.google.protobuf.Parser<Department> PARSER =
        new com.google.protobuf.AbstractParser<Department>() {
      public Department parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Department(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Department> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 deptid = 1;
    public static final int DEPTID_FIELD_NUMBER = 1;
    private int deptid_;
    /**
     * <code>required int32 deptid = 1;</code>
     */
    public boolean hasDeptid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 deptid = 1;</code>
     */
    public int getDeptid() {
      return deptid_;
    }

    // required string deptname = 2;
    public static final int DEPTNAME_FIELD_NUMBER = 2;
    private java.lang.Object deptname_;
    /**
     * <code>required string deptname = 2;</code>
     */
    public boolean hasDeptname() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string deptname = 2;</code>
     */
    public java.lang.String getDeptname() {
      java.lang.Object ref = deptname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deptname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string deptname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDeptnameBytes() {
      java.lang.Object ref = deptname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deptname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      deptid_ = 0;
      deptname_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasDeptid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDeptname()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, deptid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDeptnameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, deptid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDeptnameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.example.httpserver.protobuf.EmployeeProto.Department parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.httpserver.protobuf.EmployeeProto.Department parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.httpserver.protobuf.EmployeeProto.Department parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.httpserver.protobuf.EmployeeProto.Department parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.httpserver.protobuf.EmployeeProto.Department parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.httpserver.protobuf.EmployeeProto.Department parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.example.httpserver.protobuf.EmployeeProto.Department parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.example.httpserver.protobuf.EmployeeProto.Department parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.example.httpserver.protobuf.EmployeeProto.Department parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.httpserver.protobuf.EmployeeProto.Department parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.example.httpserver.protobuf.EmployeeProto.Department prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Department}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.example.httpserver.protobuf.EmployeeProto.DepartmentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.httpserver.protobuf.EmployeeProto.internal_static_Department_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.httpserver.protobuf.EmployeeProto.internal_static_Department_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.httpserver.protobuf.EmployeeProto.Department.class, com.example.httpserver.protobuf.EmployeeProto.Department.Builder.class);
      }

      // Construct using com.example.httpserver.protobuf.EmployeeProto.Department.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        deptid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        deptname_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.httpserver.protobuf.EmployeeProto.internal_static_Department_descriptor;
      }

      public com.example.httpserver.protobuf.EmployeeProto.Department getDefaultInstanceForType() {
        return com.example.httpserver.protobuf.EmployeeProto.Department.getDefaultInstance();
      }

      public com.example.httpserver.protobuf.EmployeeProto.Department build() {
        com.example.httpserver.protobuf.EmployeeProto.Department result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.httpserver.protobuf.EmployeeProto.Department buildPartial() {
        com.example.httpserver.protobuf.EmployeeProto.Department result = new com.example.httpserver.protobuf.EmployeeProto.Department(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.deptid_ = deptid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.deptname_ = deptname_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.httpserver.protobuf.EmployeeProto.Department) {
          return mergeFrom((com.example.httpserver.protobuf.EmployeeProto.Department)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.httpserver.protobuf.EmployeeProto.Department other) {
        if (other == com.example.httpserver.protobuf.EmployeeProto.Department.getDefaultInstance()) return this;
        if (other.hasDeptid()) {
          setDeptid(other.getDeptid());
        }
        if (other.hasDeptname()) {
          bitField0_ |= 0x00000002;
          deptname_ = other.deptname_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDeptid()) {
          
          return false;
        }
        if (!hasDeptname()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.httpserver.protobuf.EmployeeProto.Department parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.httpserver.protobuf.EmployeeProto.Department) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 deptid = 1;
      private int deptid_ ;
      /**
       * <code>required int32 deptid = 1;</code>
       */
      public boolean hasDeptid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 deptid = 1;</code>
       */
      public int getDeptid() {
        return deptid_;
      }
      /**
       * <code>required int32 deptid = 1;</code>
       */
      public Builder setDeptid(int value) {
        bitField0_ |= 0x00000001;
        deptid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 deptid = 1;</code>
       */
      public Builder clearDeptid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        deptid_ = 0;
        onChanged();
        return this;
      }

      // required string deptname = 2;
      private java.lang.Object deptname_ = "";
      /**
       * <code>required string deptname = 2;</code>
       */
      public boolean hasDeptname() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string deptname = 2;</code>
       */
      public java.lang.String getDeptname() {
        java.lang.Object ref = deptname_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          deptname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string deptname = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDeptnameBytes() {
        java.lang.Object ref = deptname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deptname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string deptname = 2;</code>
       */
      public Builder setDeptname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        deptname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string deptname = 2;</code>
       */
      public Builder clearDeptname() {
        bitField0_ = (bitField0_ & ~0x00000002);
        deptname_ = getDefaultInstance().getDeptname();
        onChanged();
        return this;
      }
      /**
       * <code>required string deptname = 2;</code>
       */
      public Builder setDeptnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        deptname_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Department)
    }

    static {
      defaultInstance = new Department(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Department)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Employee_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Employee_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Department_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Department_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Employee.proto\"n\n\010Employee\022\021\n\tfirstnam" +
      "e\030\001 \002(\t\022\020\n\010lastname\030\002 \001(\t\022\n\n\002id\030\003 \002(\005\022\026\n" +
      "\006salary\030\004 \001(\001:\006100000\022\031\n\004dept\030\005 \003(\0132\013.De" +
      "partment\".\n\nDepartment\022\016\n\006deptid\030\001 \002(\005\022\020" +
      "\n\010deptname\030\002 \002(\tB0\n\037com.example.httpserv" +
      "er.protobufB\rEmployeeProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Employee_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Employee_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Employee_descriptor,
              new java.lang.String[] { "Firstname", "Lastname", "Id", "Salary", "Dept", });
          internal_static_Department_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Department_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Department_descriptor,
              new java.lang.String[] { "Deptid", "Deptname", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
